server:
  port: 9001

spring:
    datasource:
        name: bms
        url: jdbc:mysql://localhost:3306/bms
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

## 该配置节点为独立的节点
#mybatis:
 # mapper-locations: classpath:META-NF/mapper/*.xml
  
# pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql